# Generated by Django 2.0.1 on 2018-02-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, unique=True, verbose_name='name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender')),
                ('telphone', models.CharField(max_length=20, verbose_name='telephone_number')),
                ('mobile', models.CharField(max_length=11, verbose_name='mobile_number')),
            ],
        ),
    ]
